Added NPM support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -25,6 +25,7 @@ export BUILDPACK_LOG_FILE=${BUILDPACK_LOG_FILE:-/dev/null}
 export PATH=:/usr/local/bin:$PATH
 
 # Paths.
+BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
 BIN_DIR=$(cd "$(dirname "$0")"; pwd) # absolute path
 ROOT_DIR=$(dirname "$BIN_DIR")
 BUILD_DIR=$1
@@ -215,6 +216,94 @@ if [[ ! "$BUILD_DIR" == "/app" ]]; then
   deep-cp /app/.heroku/src "$BUILD_DIR/.heroku/src"
 fi
 
+# Install NPM
+export PATH="$BUILD_DIR/.heroku/node/bin":$PATH
+
+install_nodejs() {
+  local version=${1:-8.x}
+  local dir="$2"
+
+  echo "Resolving node version $version..."
+  if ! read number url < <(curl --silent --get --retry 5 --retry-max-time 15 --data-urlencode "range=$version" "https://nodebin.herokai.com/v1/node/$platform/latest.txt"); then
+    fail_bin_install node $version;
+  fi
+
+  echo "Downloading and installing node $number..."
+  local code=$(curl "$url" -L --silent --fail --retry 5 --retry-max-time 15 -o /tmp/node.tar.gz --write-out "%{http_code}")
+  if [ "$code" != "200" ]; then
+    echo "Unable to download node: $code" && false
+  fi
+  tar xzf /tmp/node.tar.gz -C /tmp
+  rm -rf $dir/*
+  mv /tmp/node-v$number-$os-$cpu/* $dir
+  chmod +x $dir/bin/*
+}
+
+install_npm() {
+  local version="$1"
+  local dir="$2"
+  local npm_lock="$3"
+  local npm_version="$(npm --version)"
+
+  # If the user has not specified a version of npm, but has an npm lockfile
+  # upgrade them to npm 5.x if a suitable version was not installed with Node
+  if $npm_lock && [ "$version" == "" ] && [ "${npm_version:0:1}" -lt "5" ]; then
+    echo "Detected package-lock.json: defaulting npm to version 5.x.x"
+    version="5.x.x"
+  fi
+
+  if [ "$version" == "" ]; then
+    echo "Using default npm version: `npm --version`"
+  elif [[ `npm --version` == "$version" ]]; then
+    echo "npm `npm --version` already installed with node"
+  else
+    echo "Bootstrapping npm $version (replacing `npm --version`)..."
+    if ! npm install --unsafe-perm --quiet -g "npm@$version" 2>@1>/dev/null; then
+      echo "Unable to install npm $version; does it exist?" && false
+    fi
+    echo "npm `npm --version` installed"
+  fi
+}
+
+
+get_os() {
+  uname | tr A-Z a-z
+}
+
+get_cpu() {
+  if [[ "$(uname -p)" = "i686" ]]; then
+    echo "x86"
+  else
+    echo "x64"
+  fi
+}
+
+os=$(get_os)
+cpu=$(get_cpu)
+platform="$os-$cpu"
+export JQ="$BP_DIR/vendor/jq"
+
+read_json() {
+  local file=$1
+  local key=$2
+  if test -f $file; then
+    cat $file | $JQ --raw-output "$key // \"\"" || return 1
+  else
+    echo ""
+  fi
+}
+
+node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
+npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+
+echo "engines.node (package.json):  ${node_engine:-unspecified}"
+echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
+echo ""
+
+mkdir -p "$BUILD_DIR/.heroku/node"
+
+install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
+install_npm "$npm_engine" "$BUILD_DIR/.heroku/node" $NPM_LOCK
 
 # Django collectstatic support.
 let start=$(nowms)
